### ISSUE TITLE
Error response from daemon: network with name dev-network already exist

### ISSUE THREAD

**Issue by rmdhfz** [koddr/tutorial-go-fiber-rest-api#2]
**Required check list:**

- [x] I'm gonna mark the checkboxes like this.
- [ ] I didn't find in the repository's issues section similar bug.
- [x] I understand, this is Open Source and not-for-profit product.
- [ ] This is not about third-party project, framework, package or technology.

**My environment:**

- OS (`uname -a`): Windows 10
- Golang (`go version`): go1.16.7 windows/amd64

**Describe the bug:**
make docker.run
docker network inspect dev-network >/dev/null 2>&1 || \
docker network create -d bridge dev-network
The system cannot find the path specified.
Error response from daemon: network with name dev-network already exists
make: *** [Makefile:36: docker.network] Error 1

**Steps to reproduce the behavior:**

1. Go to project
2. make docker.run
3. See error

**Screenshots:**
![image](https://user-images.githubusercontent.com/39754741/130385283-14db0909-cd95-467d-9387-86eb37fe2fff.png)

**Comment by koddr** [comment]
@rmdhfz hi!

Unfortunately, I do not have a Windows 10 machine for testing these errors. My main OS is macOS, where no errors, like you mentioned.

You can try to re-write `docker network inspect dev-network >/dev/null 2>&1` command in `Makefile` for your system specific, because Windows have not `/dev/null` construction. For example, like [this](https://stackoverflow.com/a/313115) SO answer.

Anyway, your error tell us `network with name dev-network already exists`, so you can skip this step for now.
